config/routes.rb
Teikei::Application.routes.draw do

  # Define routes for regular users
  devise_for :users, controllers: { sessions: "sessions" }

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :farms, except: [:new, :edit]
      resources :depots, except: [:new, :edit]
      resources :places, only: [:index]
      resources :sessions, only: [:create, :destroy]
      resources :users, only: [:create, :show]
      resources :images, only: [:index, :show, :create, :destroy]
      match "geocode" => 'geocoder#geocode'
      resources :messages, only: [:index, :create]
      match "send_message" => "place_messages#create"
    end
  end

  ActiveAdmin.routes(self)

  root :to => "home#index"
  resources :contact_messages, only: [:new, :create]

  match "contact" => "contact_messages#new"

  match "terms" => "text_blocks#terms"
  match "about" => "text_blocks#about"
  match "imprint" => "text_blocks#imprint"

  match "faq" => "faqs#index"

  # Jasmine test engine
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/helpers/layout_helper.rb
module LayoutHelper

  def layout_render_markdown(text)
    options = { :hard_wrap => true,
                :autolink  => true,
                :no_intraemphasis => true,
                :fenced_code => true,
                :filter_html => false,
              }
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    markdown.render(text)
  end

  def layout_render_textblock(block, layout = nil)
    fmt = block.body_format.to_sym

    if fmt == :haml
      content = block.body
      type = :haml
    elsif fmt == :markdown
      content = layout_render_markdown(block.body)
      type = :html
    end

    render :inline => content, :type => type, :layout => layout
  end

end

app/views/layouts/_footer-static.html.haml
%footer.container
  .row
    .twelve.columns
      &copy; 2012-2014 Ernte teilen
      |
      = link_to t('.about_menu_item', default: 'About'), about_path, title: t('.about_menu_item_title', default: 'Click here to get background information about the project.')
      |
      = link_to t('.contact_menu_item', default: 'Contact'), contact_path, title: t('.contact_menu_item_title', default: 'Click here to write a message.')
      |
      = link_to t('.terms_menu_item', default: 'Terms & Conditions'), terms_path, title: t('.terms_menu_item_title', default: 'Click here to review the terms and conditions.')

app/views/layouts/_header-static.html.haml
.row
  %a.brand{ href: '/', title: t('application_name_title', default: 'Application name') }
    %h1
      = t('application_name', default: 'Application name')

  .description.twelve.columns
    Hier finden Landwirte und Verbraucher zusammen, die sich an
    <br/>Solidarischer Landwirtschaft beteiligen möchten.
    = link_to "/", :class => "home-button" do
      %b zur Startseite

  #user-menu
    %ul.account-menu
      - if user_signed_in?
        %li
          %b.toggle.user-name
            = current_user.name
          %ul.dropdown
            %li
              = link_to edit_user_registration_path, title: t('.edit_user_title', default: 'Click here to edit your account.') do
                %b= t('.edit_user', default: 'Edit account')
            %li
              = link_to destroy_user_session_path, method: 'delete', title: t('.sign_out_title', default: 'Click here to sign out.') do
                %b= t('.sign_out', default: 'Sign out')
      - else
        %li
          = link_to new_user_session_path, id: 'signin', title: t('.sign_in_title', default: 'Click here to sign in with an existing account.') do
            %b.toggle= t('.sign_in', default: 'Sign in')

  %ul.site-menu
    %li
      = link_to t('.contact_menu_item', default: 'Contact'), contact_path, class: 'contact-link', title: t('.contact_menu_item_title', default: 'Click here to write a message.')

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box #{name == :notice ? "success" : "alert"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.row
  %a.brand{ href: '/', title: t('application_name_title', default: 'Application name') }
    %h1
      = t('application_name', default: 'Application name')

  #user-menu
    %ul.account-menu
      - if user_signed_in?
        %li
          %b.toggle.user-name
            = current_user.name
          %ul.dropdown
            %li
              = link_to edit_user_registration_path, title: t('.edit_user_title', default: 'Click here to edit your account.') do
                %b= t('.edit_user', default: 'Edit account')
            %li
              = link_to destroy_user_session_path, method: 'delete', title: t('.sign_out_title', default: 'Click here to sign out.') do
                %b= t('.sign_out', default: 'Sign out')
      - else
        %li
          = link_to new_user_session_path, id: 'signin', title: t('.sign_in_title', default: 'Click here to sign in with an existing account.') do
            %b.toggle= t('.sign_in', default: 'Sign in')
        %li.dropdown
          = link_to new_user_registration_path, id: 'signup', title: t('.sign_up_title', default: 'Click here to sign up for a new account.') do
            %b= t('.sign_up', default: 'Sign up')

  %ul.site-menu
    %li
      = link_to t('.contact_menu_item', default: 'Contact'), contact_path, class: 'contact-link', title: t('.contact_menu_item_title', default: 'Click here to write a message.')
      / %ul.action-menu

      / %li
      /   .button.dropdown
      /     Regionen
      /     %ul.dropdown
      /       %li
      /         %a{href: '#region/mecklenburgvorpommern'} Mecklenburg-Vorpommern
      /       %li
      /         %a{href: '#region/badenwuerttemberg'} Baden-Wuerttemberg
      /       %li
      /         %a{href: '#region/schleswigholstein'} Schleswig-Holstein
      /       %li
      /         %a{href: '#region/hamburg'} Hamburg
      /       %li
      /         %a{href: '#region/niedersachsen'} Niedersachsen
      /       %li
      /         %a{href: '#region/bremen'} Bremen
      /       %li
      /         %a{href: '#region/brandenburg'} Brandenburg
      /       %li
      /         %a{href: '#region/berlin'} Berlin
      /       %li
      /         %a{href: '#region/sachsenanhalt'} Sachsen-Anhalt
      /       %li
      /         %a{href: '#region/sachsen'} Sachsen
      /       %li
      /         %a{href: '#region/thueringen'} Thueringen
      /       %li
      /         %a{href: '#region/bayern'} Bayern
      /       %li
      /         %a{href: '#region/hessen'} Hessen
      /       %li
      /         %a{href: '#region/rheinlandpfalz'} Rheinland-Pfalz
      /       %li
      /         %a{href: '#region/saarland'} Saarland
      /       %li
      /         %a{href: '#region/nordrheinwestfalen'} Nordrhein-Westfalen

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Teikei"
      %meta{:content => content_for?(:description) ? yield(:description) : "Teikei", :name => "description"}
        = csrf_meta_tags
        = yield(:head)
        = stylesheet_link_tag "application", :media => "all"
  %body{:class => "#{controller_name} #{action_name}"}
    %header.container
      = yield :header
    #main.container{:role => "main"}
      = render 'layouts/messages'
      = yield
    - if content_for?(:footer)
      = yield :footer
    - else
      = render 'layouts/footer-static'

    = javascript_include_tag "application"
    = javascript_include_tag "//use.typekit.net/cuk4pxu.js"
    :javascript
      try{Typekit.load();}catch(e){}
    = yield :javascript

app/views/layouts/static.html.haml
- content_for :header do
  = render 'layouts/header-static'
= render template: "layouts/application"